import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import ts from "typescript";
const routePath = resolve(dirname(fileURLToPath(import.meta.url)), "route.ts");
const validId = "123e4567-e89b-12d3-a456-426614174000";
const ownerOnlyMessage = "Only the employer account owner can change or disconnect this job source.";
function loadRoute() { const source = readFileSync(routePath, "utf8"); const { outputText } = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true } }); const mod = { exports: {} }; const require = (s) => { if (s === "next/server") return { NextResponse: { json: (b, i={}) => Response.json(b, i) } }; if (s.endsWith("/lib/ats/connections/manageEmployerAtsConnection")) return { updateEmployerAtsConnectionState: async () => ({ status: "updated" }), updateEmployerAtsConnectionSource: async () => ({ status: "updated" }) }; if (s.endsWith("/lib/billing")) return { getAuthUserFromRequest: async () => null }; if (s.endsWith("/lib/employerAccounts")) return { getEmployerAccountContext: async () => ({ accountId: "acct_1", canManageJobs: true, role: "account_owner" }), getSelectedEmployerAccountIdFromRequest: () => null, assertEmployerPermission: () => {} }; throw new Error(`Unexpected ${s}`); }; new Function("exports", "require", "module", outputText)(mod.exports, require, mod); return mod.exports; }
const { handleEmployerAtsConnectionActionPost } = loadRoute();
function req(body) { return new Request("https://example.com/api/employer/ats/disconnect", { method: "POST", headers: { "content-type": "application/json" }, body: typeof body === "string" ? body : JSON.stringify(body) }); }
function deps(overrides={}) { const calls = []; return { calls, getAuthUserFromRequest: async () => ({ id: "u1" }), getEmployerAccountContext: async () => ({ accountId: "acct_1", canManageJobs: true, role: "account_owner" }), getSelectedEmployerAccountIdFromRequest: () => null, assertEmployerPermission: (ctx, perm) => { assert.equal(perm, "canManageJobs"); if (!ctx.canManageJobs) { const e = new Error("secret"); e.name = "EmployerPermissionError"; throw e; } }, updateEmployerAtsConnectionState: async (input) => { calls.push(input); return { status: "updated" }; }, updateEmployerAtsConnectionSource: async () => ({ status: "updated" }), ...overrides }; }
async function json(r) { return { status: r.status, body: await r.json() }; }

test("account owner may disconnect", async () => { const d = deps(); assert.deepEqual(await json(await handleEmployerAtsConnectionActionPost(req({ connectionId: validId }), "disconnect", d)), { status: 200, body: { status: "updated" } }); assert.deepEqual(d.calls, [{ connectionId: validId, employerAccountId: "acct_1", action: "disconnect" }]); });
test("hiring manager receives 403 on disconnect and direct API action is not called", async () => { const d = deps({ getEmployerAccountContext: async () => ({ accountId: "acct_1", canManageJobs: true, role: "hiring_manager" }) }); assert.deepEqual(await json(await handleEmployerAtsConnectionActionPost(req({ connectionId: validId }), "disconnect", d)), { status: 403, body: { error: ownerOnlyMessage } }); assert.deepEqual(d.calls, []); });
test("viewer remains denied by existing canManageJobs check", async () => { const d = deps({ getEmployerAccountContext: async () => ({ accountId: "acct_1", canManageJobs: false, role: "viewer" }) }); assert.deepEqual(await json(await handleEmployerAtsConnectionActionPost(req({ connectionId: validId }), "disconnect", d)), { status: 403, body: { error: "Could not update ATS connection." } }); assert.deepEqual(d.calls, []); });
