import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import ts from "typescript";
const routePath = resolve(dirname(fileURLToPath(import.meta.url)), "route.ts");
function loadRoute() { const source = readFileSync(routePath, "utf8"); const { outputText } = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true } }); const testModule = { exports: {} }; const require = (specifier) => { if (specifier === "next/server") return { NextResponse: { json(body, init = {}) { return Response.json(body, init); } } }; if (specifier.endsWith("/lib/billing")) return { getAuthUserFromRequest: async () => null }; if (specifier.endsWith("/lib/employerAccounts")) return { getEmployerAccountContext: async () => ({ accountId: "acct_1", canManageJobs: true }), getSelectedEmployerAccountIdFromRequest: () => null, assertEmployerPermission: () => {} }; if (specifier.endsWith("/lib/supabaseAdmin")) return { getSupabaseAdminClient: () => null }; throw new Error(`Unexpected test require: ${specifier}`); }; new Function("exports", "require", "module", outputText)(testModule.exports, require, testModule); return testModule.exports; }
function request() { return new Request("https://example.com/api/employer/ats/connections", { method: "GET" }); }
async function responseJson(response) { return { status: response.status, body: await response.json() }; }
const baseConnection = { id: "conn_1", provider_key: "greenhouse", input_url: "https://example.com/careers", enabled: true, connection_status: "active", connected_at: "2026-08-01T10:00:00.000Z", last_sync_started_at: null, last_successful_sync_at: "2026-08-02T10:00:00.000Z", last_failed_sync_at: null, consecutive_failure_count: 0, employer_account_id: "leak", connected_by_user_id: "leak", source_url_key: "leak", last_failure_code: "leak" };
function dependencies(overrides = {}) { const calls = overrides.calls ?? { list: [], counts: [] }; return { getAuthUserFromRequest: async () => ({ id: "user_1", email: "owner@example.com" }), getEmployerAccountContext: async () => ({ accountId: "acct_1", canManageJobs: true, role: "account_owner" }), getSelectedEmployerAccountIdFromRequest: () => null, assertEmployerPermission: (context, permission) => { assert.equal(permission, "canManageJobs"); if (!context.canManageJobs) { const error = new Error("forbidden secret"); error.name = "EmployerPermissionError"; throw error; } }, database: { listConnections: async (accountId) => { calls.list.push(accountId); return { data: [baseConnection], error: null }; }, countImportedJobs: async (accountId, providerKey) => { calls.counts.push({ accountId, providerKey }); return { count: 24, error: null }; } }, ...overrides }; }
const { handleEmployerAtsConnectionsGet } = loadRoute();
test("unauthenticated requests return 401", async () => { const result = await responseJson(await handleEmployerAtsConnectionsGet(request(), dependencies({ getAuthUserFromRequest: async () => null }))); assert.deepEqual(result, { status: 401, body: { error: "Unauthorized." } }); });
test("no account access returns 403", async () => { const result = await responseJson(await handleEmployerAtsConnectionsGet(request(), dependencies({ getEmployerAccountContext: async () => ({ accountId: null }) }))); assert.deepEqual(result, { status: 403, body: { error: "Employer account not found." } }); });
test("no canManageJobs returns 403", async () => { const result = await responseJson(await handleEmployerAtsConnectionsGet(request(), dependencies({ getEmployerAccountContext: async () => ({ accountId: "acct_1", canManageJobs: false }) }))); assert.deepEqual(result, { status: 403, body: { error: "Could not load ATS connections." } }); });
test("only employer-owned connections are queried and returned", async () => { const calls = { list: [], counts: [] }; const result = await responseJson(await handleEmployerAtsConnectionsGet(request(), dependencies({ calls }))); assert.equal(result.status, 200); assert.deepEqual(calls.list, ["acct_1"]); assert.deepEqual(calls.counts, [{ accountId: "acct_1", providerKey: "greenhouse" }]); assert.equal(result.body.connections.length, 1); });
test("safe fields only with no provider/account/internal key leakage", async () => { const result = await responseJson(await handleEmployerAtsConnectionsGet(request(), dependencies())); assert.deepEqual(Object.keys(result.body.connections[0]).sort(), ["connectedAt", "connectionStatus", "consecutiveFailureCount", "enabled", "id", "importedJobCount", "inputUrl", "lastFailedSyncAt", "lastSuccessfulSyncAt", "lastSyncStartedAt", "sourceLabel"].sort()); const serialized = JSON.stringify(result.body); assert.doesNotMatch(serialized, /provider_key|providerKey|employerAccountId|employer_account_id|connectedByUserId|connected_by_user_id|sourceUrlKey|source_url_key|lastFailureCode|last_failure_code|leak/); });
test("empty connections return 200 with an empty array", async () => { const result = await responseJson(await handleEmployerAtsConnectionsGet(request(), dependencies({ database: { listConnections: async () => ({ data: [], error: null }), countImportedJobs: async () => { throw new Error("should not count"); } } }))); assert.deepEqual(result, { status: 200, body: { connections: [] } }); });
test("imported job count is provider-level", async () => { const result = await responseJson(await handleEmployerAtsConnectionsGet(request(), dependencies({ database: { listConnections: async () => ({ data: [{ ...baseConnection, provider_key: "Greenhouse" }, { ...baseConnection, id: "conn_2", input_url: "https://example.org/jobs", provider_key: "greenhouse" }], error: null }), countImportedJobs: async () => ({ count: 7, error: null }) } }))); assert.equal(result.status, 200); assert.deepEqual(result.body.connections.map((connection) => connection.importedJobCount), [7, 7]); });
test("safe 500 handling", async () => { const result = await responseJson(await handleEmployerAtsConnectionsGet(request(), dependencies({ database: { listConnections: async () => { throw new Error("secret database details"); }, countImportedJobs: async () => ({ count: 0, error: null }) } }))); assert.deepEqual(result, { status: 500, body: { error: "Could not load ATS connections." } }); });
