"use client";
import Link from "next/link";import {useState} from "react";import {CERTIFICATIONS,EXPERIENCE_POSITIONS,RESTAURANT_ROLES,RESPONSIBILITIES,ROLE_SKILLS,summaryFor,type RestaurantRole} from "../../../lib/resumeBuilder";import s from "./resumeBuilder.module.css";
type Exp={id:number;employer:string;position:string;location:string;startMonth:string;startYear:string;endMonth:string;endYear:string;current:boolean;bullets:string[]};
const emptyExp=(id=Date.now()):Exp=>({id,employer:"",position:"",location:"",startMonth:"",startYear:"",endMonth:"",endYear:"",current:false,bullets:[]});
const steps=["Your Information","Target Role","Experience","Skills","Education & Certifications","Preview"];
export default function ResumeBuilderClient(){const[step,setStep]=useState(0),[info,setInfo]=useState({name:"",city:"",state:"",phone:"",email:""}),[role,setRole]=useState<RestaurantRole|"">(""),[exps,setExps]=useState<Exp[]>([]),[skills,setSkills]=useState<string[]>([]),[customSkill,setCustomSkill]=useState(""),[edu,setEdu]=useState({school:"",location:"",program:"",year:""}),[certs,setCerts]=useState<string[]>([]),[otherCert,setOtherCert]=useState(""),[errors,setErrors]=useState<Record<string,string>>({});
 const updateExp=(id:number,p:Partial<Exp>)=>setExps(v=>v.map(e=>e.id===id?{...e,...p}:e));const toggle=(list:string[],value:string,set:(v:string[])=>void)=>set(list.includes(value)?list.filter(x=>x!==value):[...list,value]);
 function next(){const e:Record<string,string>={};if(step===0&&!info.name.trim())e.name="Enter your full name.";if(step===1&&!role)e.role="Choose a target role.";if(step===2)exps.forEach(x=>{if((x.employer||x.position||x.location||x.bullets.length)&&!x.employer)e[`employer${x.id}`]="Enter an employer.";if((x.employer||x.position||x.location||x.bullets.length)&&!x.position)e[`position${x.id}`]="Choose a position."});setErrors(e);if(!Object.keys(e).length)setStep(v=>Math.min(5,v+1));}
 function chooseRole(r:RestaurantRole){setRole(r);if(!skills.length)setSkills(ROLE_SKILLS[r].slice(0,4));}
 function startOver(){if(confirm("Start over and erase everything entered in this resume?")){setInfo({name:"",city:"",state:"",phone:"",email:""});setRole("");setExps([]);setSkills([]);setEdu({school:"",location:"",program:"",year:""});setCerts([]);setStep(0);setErrors({});}}
 return <main className={s.page}><header className={`${s.intro} ${s.noPrint}`}><p className={s.eyebrow}>FREE CANDIDATE TOOL</p><h1>Restaurant Resume Builder</h1><p>Build a professional, restaurant-ready resume one simple step at a time.</p></header><section className={s.shell}><nav className={`${s.progress} ${s.noPrint}`} aria-label="Resume builder progress">{steps.map((x,i)=><button key={x} aria-current={i===step?"step":undefined} onClick={()=>i<step&&setStep(i)} disabled={i>step}><b>{i+1}</b><span>{x}</span></button>)}</nav>
 <div className={step===5?s.previewWrap:s.card}>{step===0&&<><h2>Your Information</h2><p className={s.help}>City and state are enough for most resumes. You do not need to include your full street address.</p><div className={s.formGrid}><Field label="Full Name" id="name" required value={info.name} onChange={v=>setInfo({...info,name:v})} error={errors.name}/><Field label="City" id="city" value={info.city} onChange={v=>setInfo({...info,city:v})}/><Field label="State" id="state" value={info.state} onChange={v=>setInfo({...info,state:v})}/><Field label="Phone Number" id="phone" value={info.phone} onChange={v=>setInfo({...info,phone:v})}/><Field label="Email Address" id="email" type="email" value={info.email} onChange={v=>setInfo({...info,email:v})}/></div></>}
 {step===1&&<><h2>What restaurant position are you targeting?</h2><div className={s.choices}>{RESTAURANT_ROLES.map(r=><button type="button" className={role===r?s.selected:""} aria-pressed={role===r} onClick={()=>chooseRole(r)} key={r}>{r}</button>)}</div>{errors.role&&<p className={s.error}>{errors.role}</p>}</>}
 {step===2&&<><h2>Work Experience</h2><p className={s.help}>Restaurant experience is not required. Add any work that shows your transferable skills.</p>{exps.map((e,index)=><article className={s.experience} key={e.id}><div className={s.row}><h3>Experience {index+1}</h3><button className={s.textButton} onClick={()=>setExps(v=>v.filter(x=>x.id!==e.id))}>Remove</button></div><div className={s.formGrid}><Field label="Employer / Restaurant Name" id={`employer${e.id}`} value={e.employer} onChange={v=>updateExp(e.id,{employer:v})} error={errors[`employer${e.id}`]}/><label>Position<select value={e.position} onChange={x=>updateExp(e.id,{position:x.target.value,bullets:[]})}><option value="">Select a position</option>{EXPERIENCE_POSITIONS.map(x=><option key={x}>{x}</option>)}</select>{errors[`position${e.id}`]&&<span className={s.error}>{errors[`position${e.id}`]}</span>}</label><Field label="City / State" id={`location${e.id}`} value={e.location} onChange={v=>updateExp(e.id,{location:v})}/><Field label="Start Month" id={`sm${e.id}`} value={e.startMonth} onChange={v=>updateExp(e.id,{startMonth:v})}/><Field label="Start Year" id={`sy${e.id}`} value={e.startYear} onChange={v=>updateExp(e.id,{startYear:v})}/><Field label="End Month" id={`em${e.id}`} value={e.endMonth} disabled={e.current} onChange={v=>updateExp(e.id,{endMonth:v})}/><Field label="End Year" id={`ey${e.id}`} value={e.endYear} disabled={e.current} onChange={v=>updateExp(e.id,{endYear:v})}/></div><label className={s.check}><input type="checkbox" checked={e.current} onChange={x=>updateExp(e.id,{current:x.target.checked})}/> I currently work here</label>{e.position&&<ResponsibilityPicker exp={e} update={updateExp}/>}</article>)}<button className={s.secondary} onClick={()=>setExps(v=>[...v,emptyExp()])}>+ Add Experience</button></>}
 {step===3&&role&&<><h2>Skills for {role}</h2><p className={s.help}>Choose skills you can confidently discuss with an employer.</p><div className={s.choices}>{ROLE_SKILLS[role].map(x=><button type="button" aria-pressed={skills.includes(x)} className={skills.includes(x)?s.selected:""} onClick={()=>toggle(skills,x,setSkills)} key={x}>{skills.includes(x)?"✓ ":""}{x}</button>)}</div><AddItem label="Add a custom skill" value={customSkill} setValue={setCustomSkill} add={()=>{if(customSkill.trim()&&!skills.includes(customSkill.trim()))setSkills([...skills,customSkill.trim()]);setCustomSkill("")}}/><Selected items={skills} remove={x=>setSkills(skills.filter(y=>y!==x))}/></>}
 {step===4&&<><h2>Education & Certifications</h2><p className={s.help}>Both sections are optional.</p><h3>Education</h3><div className={s.formGrid}><Field label="School Name" id="school" value={edu.school} onChange={v=>setEdu({...edu,school:v})}/><Field label="City / State" id="eduloc" value={edu.location} onChange={v=>setEdu({...edu,location:v})}/><Field label="Degree / Diploma / Program" id="program" value={edu.program} onChange={v=>setEdu({...edu,program:v})}/><Field label="Graduation Year" id="grad" value={edu.year} onChange={v=>setEdu({...edu,year:v})}/></div><h3>Certifications</h3><div className={s.choices}>{CERTIFICATIONS.map(x=><button type="button" aria-pressed={certs.includes(x)} className={certs.includes(x)?s.selected:""} onClick={()=>toggle(certs,x,setCerts)} key={x}>{x}</button>)}</div>{certs.includes("Other")&&<Field label="Other certification" id="othercert" value={otherCert} onChange={setOtherCert}/>}</>}
 {step===5&&role&&<Preview info={info} role={role} exps={exps} skills={skills} edu={edu} certs={certs.filter(x=>x!=="Other").concat(otherCert?otherCert:[])}/>}</div>
 <div className={`${s.actions} ${s.noPrint}`}>{step>0&&<button className={s.secondary} onClick={()=>setStep(v=>v-1)}>{step===5?"Back to Edit":"Back"}</button>}<button className={s.startOver} onClick={startOver}>Start Over</button>{step<5&&<button className={s.primary} onClick={next}>{step===4?"Preview Resume":"Continue"} →</button>}{step===5&&<button className={s.primary} onClick={()=>window.print()}>Download / Print Resume</button>}</div>{step===5&&<aside className={`${s.jobs} ${s.noPrint}`}><h2>Ready to Put Your Resume to Work?</h2><Link href="/jobs">Find Restaurant Jobs →</Link></aside>}</section></main>}
function Field({label,id,value,onChange,error,type="text",required=false,disabled=false}:{label:string;id:string;value:string;onChange:(v:string)=>void;error?:string;type?:string;required?:boolean;disabled?:boolean}){return <label htmlFor={id}>{label}{required&&" *"}<input id={id} type={type} value={value} disabled={disabled} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined} onChange={e=>onChange(e.target.value)}/>{error&&<span id={`${id}-error`} className={s.error}>{error}</span>}</label>}
function AddItem({label,value,setValue,add}:{label:string;value:string;setValue:(v:string)=>void;add:()=>void}){return <div className={s.add}><label>{label}<input value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();add()}}}/></label><button className={s.secondary} onClick={add}>Add</button></div>}
function Selected({items,remove}:{items:string[];remove:(x:string)=>void}){return <ul className={s.tags}>{items.map(x=><li key={x}>{x}<button aria-label={`Remove ${x}`} onClick={()=>remove(x)}>×</button></li>)}</ul>}
function ResponsibilityPicker({exp,update}:{exp:Exp;update:(id:number,p:Partial<Exp>)=>void}){const[v,setV]=useState("");const suggestions=RESPONSIBILITIES[exp.position]||RESPONSIBILITIES.Other;return <div><h4>Suggested responsibilities</h4><div className={s.choices}>{suggestions.map(x=><button key={x} aria-pressed={exp.bullets.includes(x)} className={exp.bullets.includes(x)?s.selected:""} onClick={()=>update(exp.id,{bullets:exp.bullets.includes(x)?exp.bullets.filter(y=>y!==x):[...exp.bullets,x]})}>{exp.bullets.includes(x)?"✓ ":""}{x}</button>)}</div><AddItem label="Write your own responsibility" value={v} setValue={setV} add={()=>{if(v.trim())update(exp.id,{bullets:[...exp.bullets,v.trim()]});setV("")}}/><Selected items={exp.bullets} remove={x=>update(exp.id,{bullets:exp.bullets.filter(y=>y!==x)})}/></div>}
function Preview({info,role,exps,skills,edu,certs}:{info:{name:string;city:string;state:string;phone:string;email:string};role:RestaurantRole;exps:Exp[];skills:string[];edu:{school:string;location:string;program:string;year:string};certs:string[]}){const contact=[[info.city,info.state].filter(Boolean).join(", "),info.phone,info.email].filter(Boolean);return <article className={s.resume} id="resume-preview"><header><h1>{info.name}</h1>{contact.length>0&&<p>{contact.join(" • ")}</p>}<h2>{role}</h2></header><Section title="Professional Summary"><p>{summaryFor(role,skills,exps.length)}</p></Section>{exps.length>0&&<Section title="Experience">{exps.map(e=><div className={s.resumeEntry} key={e.id}><h3>{e.position} <span>— {e.employer}</span></h3><p>{e.location}{e.location&&e.startYear?" • ":""}{[e.startMonth,e.startYear].filter(Boolean).join(" ")}{e.startYear?" – ":""}{e.current?"Present":[e.endMonth,e.endYear].filter(Boolean).join(" ")}</p>{e.bullets.length>0&&<ul>{e.bullets.map(x=><li key={x}>{x}</li>)}</ul>}</div>)}</Section>}{skills.length>0&&<Section title="Skills"><p>{skills.join(" • ")}</p></Section>}{edu.school&&<Section title="Education"><h3>{edu.school}</h3><p>{[edu.program,edu.location,edu.year].filter(Boolean).join(" • ")}</p></Section>}{certs.length>0&&<Section title="Certifications"><p>{certs.join(" • ")}</p></Section>}<footer>Created with Restaurants Now Hiring</footer></article>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h2>{title}</h2>{children}</section>}
