"use client";
import Link from "next/link";
import {useState} from "react";
import {PRACTICE_MODES,RESTAURANT_ROLES,selectQuestions,type Assessment,type PracticeMode,type Question,type RestaurantRole} from "../../../lib/interviewPractice";
import styles from "./interviewPractice.module.css";
type Response={answer:string;assessment?:Assessment;skipped?:boolean;coaching?:boolean};
const assessments:Assessment[]=["Confident","Needs Practice","Not Sure"];
const finalTips=["Arrive 10–15 minutes early.","Dress cleanly and appropriately for the restaurant.","Bring a copy of your resume.","Know your availability before the interview.","Be ready to explain why you want the role.","Use specific examples when answering behavioral questions.","Show that you understand teamwork and guest service.","Prepare at least one question to ask the interviewer."];
export default function InterviewPracticeClient(){
 const [step,setStep]=useState<"landing"|"role"|"mode"|"interview"|"results">("landing");const [role,setRole]=useState<RestaurantRole>();const [otherRole,setOtherRole]=useState("");const [mode,setMode]=useState<PracticeMode>();const [questions,setQuestions]=useState<Question[]>([]);const [index,setIndex]=useState(0);const [responses,setResponses]=useState<Record<string,Response>>({});
 const displayRole=role==="Other"?otherRole:role; const current=questions[index]; const response=current?responses[current.id]??{answer:""}:undefined;
 const start=(chosen:PracticeMode)=>{if(!role)return;setMode(chosen);setQuestions(selectQuestions(role,chosen));setIndex(0);setResponses({});setStep("interview")};
 const update=(value:Partial<Response>)=>setResponses(old=>({...old,[current.id]:{...old[current.id],...value,answer:value.answer??old[current.id]?.answer??""}}));
 const next=()=>{if(index===questions.length-1)setStep("results");else setIndex(index+1)};
 const restart=()=>{const active=Object.values(responses).some(r=>r.answer);if(active&&!window.confirm("Start over and erase your interview answers?"))return;setStep("landing");setRole(undefined);setOtherRole("");setMode(undefined);setQuestions([]);setResponses({});};
 return <main className={styles.page}>{step!=="landing"&&<button className={styles.restart} onClick={restart}>Start over</button>}
 {step==="landing"&&<section className={`${styles.hero} ${styles.landingPanel}`}><span className={styles.eyebrow}>CANDIDATE RESOURCES</span><h1>Practice Your Restaurant Interview</h1><p className={styles.lead}>Build confidence before your next restaurant interview with role-specific questions and practical coaching.</p><div className={styles.featureGrid}><div><span aria-hidden="true">1</span><strong>Choose your restaurant role</strong></div><div><span aria-hidden="true">2</span><strong>Practice realistic questions</strong></div><div><span aria-hidden="true">3</span><strong>Get practical coaching</strong></div><div><span aria-hidden="true">4</span><strong>Review what to work on</strong></div></div><button onClick={()=>setStep("role")}>Start Interview Practice</button><p className={styles.privacy}>Your answers stay in this browser session and are not submitted.</p></section>}
 {step==="role"&&<section className={styles.panel}><span className={styles.eyebrow}>STEP 1 OF 2</span><h1>What position are you interviewing for?</h1><fieldset className={styles.choiceGrid}><legend className={styles.srOnly}>Restaurant position</legend>{RESTAURANT_ROLES.map(item=><label className={styles.choice} key={item}><input type="radio" name="role" checked={role===item} onChange={()=>setRole(item)}/><span>{item}</span></label>)}</fieldset>{role==="Other"&&<label className={styles.field}>Position name<input value={otherRole} onChange={e=>setOtherRole(e.target.value)} placeholder="Enter the position"/></label>}<div className={styles.actions}><button className={styles.secondary} onClick={()=>setStep("landing")}>Back</button><button disabled={!role||(role==="Other"&&!otherRole.trim())} onClick={()=>setStep("mode")}>Continue →</button></div></section>}
 {step==="mode"&&<section className={styles.panel}><span className={styles.eyebrow}>STEP 2 OF 2</span><h1>Choose your practice type</h1><p>Practicing for: <strong>{displayRole}</strong></p><div className={styles.modeGrid}>{(Object.entries(PRACTICE_MODES) as [PracticeMode,typeof PRACTICE_MODES[PracticeMode]][]).map(([key,item])=><button className={styles.mode} key={key} onClick={()=>start(key)}><strong>{item.name}</strong><span>{item.count} {key==="tough"?"challenging ":""}questions</span><small>{item.description}</small></button>)}</div><button className={styles.secondary} onClick={()=>setStep("role")}>← Change role</button></section>}
 {step==="interview"&&current&&response&&<section className={styles.panel} aria-live="polite"><div className={styles.progress}><span>Question {index+1} of {questions.length}</span><span>Practicing for: <strong>{displayRole}</strong></span></div><div className={styles.bar}><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div><span className={styles.category}>{current.category}</span><h1>{current.prompt}</h1><label className={styles.field}>Your answer<textarea value={response.answer} onChange={e=>update({answer:e.target.value,skipped:false})} placeholder="Type your answer here..."/></label>{!response.coaching?<div className={styles.actions}><button className={styles.secondary} disabled={index===0} onClick={()=>setIndex(index-1)}>← Previous</button><button className={styles.skip} onClick={()=>{update({skipped:true});next()}}>Skip Question</button><button onClick={()=>update({coaching:true})}>Get Coaching</button></div>:<div className={styles.coaching}><h2>What a strong answer should include</h2><ul>{current.coaching.map(point=><li key={point}>{point}</li>)}</ul>{current.star&&<div className={styles.star}><h3>Use the STAR method</h3><p><strong>Situation</strong> — What was happening?</p><p><strong>Task</strong> — What needed to be done?</p><p><strong>Action</strong> — What did you do?</p><p><strong>Result</strong> — What happened?</p></div>}<h2>Interview Tip</h2><p>{current.tip}</p><fieldset className={styles.assess}><legend>How do you feel about your answer?</legend>{assessments.map(item=><label key={item}><input type="radio" name="assessment" checked={response.assessment===item} onChange={()=>update({assessment:item})}/><span>{item}</span></label>)}</fieldset><div className={styles.actions}><button className={styles.secondary} disabled={index===0} onClick={()=>setIndex(index-1)}>← Previous</button><button disabled={!response.assessment} onClick={next}>{index===questions.length-1?"See My Summary →":"Next Question →"}</button></div></div>}</section>}
 {step==="results"&&<Results role={displayRole||"Other"} mode={mode!} questions={questions} responses={responses} restart={restart}/>}</main>
}
function Results({role,mode,questions,responses,restart}:{role:string;mode:PracticeMode;questions:Question[];responses:Record<string,Response>;restart:()=>void}){const counts=Object.fromEntries(assessments.map(a=>[a,Object.values(responses).filter(r=>r.assessment===a).length]));const review=questions.filter(q=>["Needs Practice","Not Sure"].includes(responses[q.id]?.assessment||""));return <section className={styles.panel}><span className={styles.eyebrow}>PRACTICE SUMMARY</span><h1>Interview Practice Complete</h1><div className={styles.summary}><div><span>Role practiced</span><strong>{role}</strong></div><div><span>Practice type</span><strong>{PRACTICE_MODES[mode].name}</strong></div><div><span>Questions completed</span><strong>{questions.filter(q=>responses[q.id]?.assessment).length}</strong></div><div><span>Questions skipped</span><strong>{questions.filter(q=>responses[q.id]?.skipped).length}</strong></div></div><h2>Your Confidence</h2><div className={styles.confidence}>{assessments.map(a=><div key={a}><strong>{counts[a]}</strong><span>{a}</span></div>)}</div><h2>Questions to Review</h2>{review.length?<div className={styles.review}>{review.map(q=><article key={q.id}><h3>{q.prompt}</h3><h4>Your answer</h4><p>{responses[q.id]?.answer||<em>No answer entered.</em>}</p><h4>Coaching tips</h4><ul>{q.coaching.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div>:<p>You did not mark any questions for review this time.</p>}<h2>Final Interview Tips</h2><ul className={styles.checklist}>{finalTips.map(x=><li key={x}>{x}</li>)}</ul><div className={styles.actions}><button onClick={restart}>Practice Again</button><Link className={styles.buttonLink} href="/jobs">Find Restaurant Jobs →</Link><Link className={styles.textLink} href="/candidate-resources/resume-builder">Build Your Resume →</Link></div></section>}
