export const SCHEDULE_OPTIONS = [
  "Day shift",
  "Night shift",
  "Morning shift",
  "Evening shift",
  "Overnight shift",
  "Weekends required",
  "Weekdays only (M-F)",
  "Flexible schedule",
  "Rotating schedule",
  "On-call",
  "Overtime",
  "No weekends",
  "Choose your own hours",
  "Other",
];

export const BENEFIT_OPTIONS = [
  "Health insurance",
  "Dental insurance",
  "Vision insurance",
  "401(k)",
  "Paid time off",
  "Flexible schedule",
  "Employee discount",
  "Free meals",
  "Tuition assistance",
  "Paid training",
  "Referral bonus",
  "Bonus pay",
  "Overtime available",
  "Career growth",
  "Other",
];
