export const RESTAURANT_ROLES = ["Server","Bartender","Host / Hostess","Cashier","Line Cook","Prep Cook","Dishwasher","Shift Leader","Kitchen Manager","Restaurant Manager","General Manager"] as const;
export type RestaurantRole = typeof RESTAURANT_ROLES[number];
export const EXPERIENCE_POSITIONS = [...RESTAURANT_ROLES, "Other"] as const;

const generic = ["Provided customer service","Worked effectively in a fast-paced environment","Handled cash and payment transactions","Maintained organized work areas","Followed company policies and procedures","Worked collaboratively with team members","Managed multiple priorities","Communicated professionally with customers and coworkers","Completed assigned tasks accurately and on time","Trained or assisted new team members"];
export const RESPONSIBILITIES: Record<string,string[]> = {
 Server:["Provided friendly and attentive guest service","Managed multiple tables during high-volume shifts","Entered guest orders accurately using POS systems","Processed cash and credit card payments","Recommended menu items and promoted specials","Maintained knowledge of menu items and ingredients","Worked closely with kitchen and support staff","Completed opening and closing side work","Addressed guest concerns professionally","Maintained clean and organized dining areas"],
 Bartender:["Prepared alcoholic and non-alcoholic beverages","Provided bar guests with attentive service","Maintained knowledge of cocktails, beer and wine","Processed payments using POS systems","Verified identification and followed alcohol-service policies","Restocked bar inventory during shifts","Maintained a clean and organized bar","Managed multiple drink orders during high-volume periods","Recommended beverages and menu items","Assisted with opening and closing duties"],
 "Host / Hostess":["Welcomed guests and managed the seating flow","Maintained accurate wait lists and reservations","Answered guest questions in person and by phone","Communicated table status with service staff","Kept entry and host areas clean and organized"],
 Cashier:["Processed cash and card transactions accurately","Greeted customers and answered menu questions","Entered orders accurately using POS systems","Balanced the register and followed cash-handling procedures","Maintained a clean and organized service area"],
 "Line Cook":["Prepared menu items according to recipes and standards","Set up and maintained an organized station","Coordinated ticket timing with the kitchen team","Followed food safety and sanitation procedures","Completed station closing and proper food storage"],
 "Prep Cook":["Prepared ingredients according to recipes and prep lists","Used knives and kitchen equipment safely","Labeled, dated and stored food properly","Maintained clean and sanitized prep areas","Supported line cooks during busy service periods"],
 Dishwasher:["Washed and sanitized dishes, cookware and utensils","Maintained clean dish and kitchen areas","Restocked clean dishes for kitchen and service teams","Removed waste and followed sanitation procedures","Supported kitchen cleaning and closing duties"],
 "Shift Leader":["Coordinated team members during assigned shifts","Supported guest service and resolved concerns","Completed opening and closing procedures","Trained and assisted team members","Monitored food safety, cleanliness and service standards"],
 "Kitchen Manager":["Supported daily kitchen operations and service execution","Coached kitchen team members on recipes and standards","Monitored inventory, food storage and sanitation","Coordinated prep and station coverage","Maintained food quality and safety standards"],
 "Restaurant Manager":["Supported daily restaurant operations and guest service","Led shifts and coached team members","Resolved guest concerns professionally","Monitored labor, inventory and operating standards","Supported scheduling, training and opening and closing procedures"],
 "General Manager":["Directed daily restaurant operations and service standards","Developed and coached restaurant team members","Oversaw scheduling, inventory and cost controls","Supported hiring, onboarding and performance management","Maintained guest satisfaction, safety and brand standards"],
 Other:generic
};
export const ROLE_SKILLS: Record<RestaurantRole,string[]> = {
 Server:["Guest Service","Customer Service","Teamwork","POS Systems","Menu Knowledge","Table Service"], Bartender:["Guest Service","Alcohol Service","POS Systems","Cash Handling","Menu Knowledge","High-Volume Service"], "Host / Hostess":["Guest Service","Communication","Reservation Systems","Teamwork","Guest Recovery"], Cashier:["Customer Service","POS Systems","Cash Handling","Communication","Multitasking"], "Line Cook":["Food Preparation","Knife Skills","Line Setup","Recipe Execution","Kitchen Sanitation","Teamwork"], "Prep Cook":["Food Preparation","Knife Skills","Food Storage","Kitchen Sanitation","Recipe Execution"], Dishwasher:["Cleaning & Sanitation","Teamwork","Time Management","Food Safety","Closing Procedures"], "Shift Leader":["Shift Management","Team Leadership","Staff Training","Guest Recovery","Opening & Closing Procedures"], "Kitchen Manager":["Team Leadership","Inventory Management","Food Cost Control","Kitchen Sanitation","Scheduling","Restaurant Operations"], "Restaurant Manager":["Restaurant Operations","Team Leadership","Coaching","Shift Management","Labor Management","Guest Recovery"], "General Manager":["Restaurant Operations","Team Leadership","Hiring & Onboarding","Labor Management","Food Cost Control","Conflict Resolution"]
};
export const CERTIFICATIONS=["ServSafe Food Handler","ServSafe Manager","ServSafe Alcohol","TIPS","Food Handler Card","Alcohol Service Certification","CPR / First Aid","Other"];
export type ExperienceDraft = { employer:string; position:string; location:string; startMonth:string; startYear:string; endMonth:string; endYear:string; current:boolean; bullets:string[] };
export function isEmptyExperience(experience: ExperienceDraft){return !experience.employer.trim()&&!experience.position.trim()&&!experience.location.trim()&&!experience.startMonth.trim()&&!experience.startYear.trim()&&!experience.endMonth.trim()&&!experience.endYear.trim()&&!experience.current&&experience.bullets.length===0;}
export function summaryFor(role: RestaurantRole, skills:string[], experienceCount:number){const selected=(skills.length?skills:ROLE_SKILLS[role]).slice(0,4).join(", ");const intro=role.includes("Cook")||role==="Dishwasher"?"Dependable kitchen professional":role.includes("Manager")||role==="Shift Leader"?"Restaurant leadership professional":"Guest-focused restaurant professional";return `${intro}${experienceCount?" with experience working in fast-paced environments":" ready to contribute in a fast-paced environment"}. Skilled in ${selected}.`;}
