import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const migration=fs.readFileSync("supabase/migrations/202608270001_rnh_sourced_jobs.sql","utf8");
const detail=fs.readFileSync("app/jobs/[id]/page.tsx","utf8");
const event=fs.readFileSync("app/components/JobEngagement.tsx","utf8");
const adminRoute=fs.readFileSync("app/api/admin/sourced-jobs/route.ts","utf8");
const adminUi=fs.readFileSync("app/admin/sourced-jobs/SourcedJobsClient.tsx","utf8");
test("employer flow remains while sourced jobs use external CTA and disclosure",()=>{assert.match(detail,/!isSourced \? <CandidateSubmissionForm/);assert.match(detail,/APPLY ON COMPANY SITE|JobEngagement/);assert.match(detail,/not representing the employer/)});
test("events are anonymous and same-session views are unique",()=>{assert.match(migration,/job_events_unique_session_view_idx/);assert.match(migration,/where event_type = 'job_view'/);assert.doesNotMatch(migration,/ip_address/);assert.match(event,/job_view/);assert.match(event,/apply_click/)});
test("verified claims retire, but inserts do not",()=>{assert.match(migration,/old.status is distinct from 'verified'/);assert.match(migration,/retired_reason='employer_claimed'/);assert.match(migration,/Employers can request claims/)});
test("sourced mutation is admin/service-only",()=>{assert.match(migration,/source_type='employer'/);assert.match(migration,/Admin writes use the service role/)});
test("new sourced jobs default active with server-generated verification dates",()=>{assert.match(adminRoute,/\? body\.status : "active"/);assert.match(adminRoute,/const lastVerified = new Date\(\)\.toISOString\(\)/);assert.match(adminRoute,/review_due_at: nextReviewDate/);assert.doesNotMatch(adminUi,/name="lastVerifiedAt"|name="reviewDueAt"/)});
test("company website is saved while matching companies are reused",()=>{assert.match(adminUi,/name="companyWebsite"/);assert.match(adminRoute,/toLocaleLowerCase/);assert.match(adminRoute,/update\(\{ website: companyWebsite/);assert.match(adminRoute,/insert\(\{ name: companyName, website:/)});
test("admin form uses application employment values and keeps URL validation",()=>{assert.match(adminUi,/EMPLOYMENT_OPTIONS/);assert.match(adminRoute,/isOfficialSourceUrl\(body\.sourceUrl\)/);assert.match(adminRoute,/isOfficialSourceUrl\(body\.externalApplyUrl\)/)});
test("analytics and employer application branches remain present",()=>{assert.match(adminRoute,/applyClickRate/);assert.match(adminRoute,/uniqueViewers/);assert.match(detail,/!isSourced \? <CandidateSubmissionForm/)});
