import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const migration=fs.readFileSync("supabase/migrations/202608270001_rnh_sourced_jobs.sql","utf8");
const detail=fs.readFileSync("app/jobs/[id]/page.tsx","utf8");
const event=fs.readFileSync("app/components/JobEngagement.tsx","utf8");
test("employer flow remains while sourced jobs use external CTA and disclosure",()=>{assert.match(detail,/!isSourced \? <CandidateSubmissionForm/);assert.match(detail,/APPLY ON COMPANY SITE|JobEngagement/);assert.match(detail,/not representing the employer/)});
test("events are anonymous and same-session views are unique",()=>{assert.match(migration,/job_events_unique_session_view_idx/);assert.match(migration,/where event_type = 'job_view'/);assert.doesNotMatch(migration,/ip_address/);assert.match(event,/job_view/);assert.match(event,/apply_click/)});
test("verified claims retire, but inserts do not",()=>{assert.match(migration,/old.status is distinct from 'verified'/);assert.match(migration,/retired_reason='employer_claimed'/);assert.match(migration,/Employers can request claims/)});
test("sourced mutation is admin/service-only",()=>{assert.match(migration,/source_type='employer'/);assert.match(migration,/Admin writes use the service role/)});
