import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import ts from "typescript";
const read = (path) => readFile(new URL(`../../${path}`, import.meta.url), "utf8");
async function moduleUnderTest() { const source=await read("lib/candidateResources.ts"); const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText; return import(`data:text/javascript;base64,${Buffer.from(js).toString("base64")}`); }
const sample=(overrides={})=>({id:crypto.randomUUID(),title:"Resource",category:"Resume Help",resource_type:"article",url:"https://example.com",source:"Example",description:null,thumbnail_url:null,sort_order:1,active:true,created_at:"",updated_at:"",...overrides});
test("public route exists, requests only active rows, and navigation links to it",async()=>{const [page,nav]=await Promise.all([read("app/candidate-resources/page.tsx"),read("app/components/TopBanner.tsx")]);assert.match(page,/\.eq\("active", true\)/);assert.match(nav,/href: "\/candidate-resources"/)});
test("active-only filtering, category filtering, and sort order are deterministic",async()=>{const {visibleResources}=await moduleUnderTest();const rows=[sample({title:"Second",sort_order:2}),sample({title:"Hidden",active:false,sort_order:0}),sample({title:"First",sort_order:1}),sample({title:"Video",category:"What to Wear",resource_type:"video"})];assert.deepEqual(visibleResources(rows).map(x=>x.title),["First","Video","Second"]);assert.deepEqual(visibleResources(rows,"Resume Help").map(x=>x.title),["First","Second"])});
test("video and article treatments and safe external link attributes render",async()=>{const client=await read("app/candidate-resources/CandidateResourcesClient.tsx");assert.match(client,/Watch Video/);assert.match(client,/Read Article/);assert.match(client,/target="_blank" rel="noopener noreferrer"/);assert.match(client,/youtubeThumbnail/)});
test("candidate tools activate only the resume and jobs routes",async()=>{const client=await read("app/candidate-resources/CandidateResourcesClient.tsx");for(const title of ["BUILD YOUR RESUME","PRACTICE AN INTERVIEW","EXPLORE RESTAURANT CAREERS","FIND YOUR NEXT JOB"])assert.ok(client.includes(title),title);assert.equal((client.match(/Coming Soon/g)??[]).length,1);assert.match(client,/href: "\/jobs"/);assert.match(client,/href: "\/candidate-resources\/resume-builder"/);assert.match(client,/Start Building/)});
test("expanded page metadata describes restaurant career resources",async()=>{const page=await read("app/candidate-resources/page.tsx");assert.match(page,/title: "Restaurant Career Resources"/);assert.doesNotMatch(page,/Restaurant Career Resources \| Restaurants Now Hiring/);assert.match(page,/interview preparation, career guides, job search resources/)});
test("admin page and every CRUD handler use existing admin authorization",async()=>{const files=await Promise.all([read("app/admin/candidate-resources/page.tsx"),read("app/api/admin/candidate-resources/route.ts"),read("app/api/admin/candidate-resources/[id]/route.ts")]);assert.match(files[0],/getAdminUserFromAccessToken/);assert.ok((files[1].match(/requireAdminApi/g)?.length ?? 0) >= 3);assert.ok((files[2].match(/requireAdminApi/g)?.length ?? 0) >= 3)});
test("admin supports create, edit, hide, delete, search, and filters",async()=>{const ui=await read("app/admin/candidate-resources/CandidateResourcesAdmin.tsx");for(const token of ['method:editing?"PUT":"POST"','method:"DELETE"','active:!i.active','Search resources','Filter by category','Filter by type','Filter by status'])assert.ok(ui.includes(token),token)});
test("migration permits incomplete hidden drafts but requires URLs to publish",async()=>{const sql=await read("supabase/migrations/202608180001_candidate_resources.sql");assert.match(sql,/not active or url is not null/);assert.match(sql,/using \(active = true\)/);assert.doesNotMatch(sql,/for (insert|update|delete) to anon/i)});
