"use client";
import Link from "next/link"; import {useCallback,useEffect,useMemo,useState} from "react";
type Job={id:string;restaurant_name:string;title:string;city:string;state:string;status:string;last_verified_at:string;review_due_at:string;active:boolean};
type Analytics={companyId:string;companyName:string;activeSourcedJobs:number;totalJobViews:number;uniqueViewers:number;applyClicks:number;applyClickRate:number;readyForOutreach:boolean;jobs:{id:string;title:string;views:number;uniqueViewers:number;applyClicks:number}[]};
const input:React.CSSProperties={padding:"10px 12px",border:"1px solid #ccc",borderRadius:8,width:"100%"};
export default function SourcedJobsClient(){const [jobs,setJobs]=useState<Job[]>([]),[analytics,setAnalytics]=useState<Analytics[]>([]),[filter,setFilter]=useState("all"),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/admin/sourced-jobs");const b=await r.json();if(r.ok){setJobs(b.jobs||[]);setAnalytics(b.analytics||[])}else setMessage(b.error);},[]);useEffect(()=>{void load()},[load]);
 const shown=useMemo(()=>jobs.filter(j=>filter==="all"||filter==="review"&&new Date(j.review_due_at)<=new Date()||j.status===filter),[jobs,filter]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const body=Object.fromEntries(form);const r=await fetch("/api/admin/sourced-jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const b=await r.json().catch(()=>({}));setMessage(r.ok?"Sourced job saved.":b.error);if(r.ok){e.currentTarget.reset();await load();}}
 async function action(id:string,action:string){const r=await fetch(`/api/admin/sourced-jobs/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});setMessage(r.ok?`Job ${action} action completed.`:"Action failed.");await load();}
 return <main style={{maxWidth:1180,margin:"80px auto",padding:20,fontFamily:"var(--font-body)"}}><Link href="/admin">← Admin</Link><h1 style={{color:"#35806e"}}>RNH Sourced Jobs</h1><p>Manually add only public opportunities from an employer’s official careers site or official ATS. Write a short original RNH summary; do not copy full descriptions from job boards.</p>{message&&<p role="status"><b>{message}</b></p>}
 <form onSubmit={submit} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12,background:"#f7faf9",padding:18,borderRadius:12}}>
 {[["companyName","Company"],["title","Job Title"],["city","City"],["state","State"],["employmentType","Employment Type"],["payRange","Pay / Pay Range"],["sourceUrl","Official Job Source URL"],["externalApplyUrl","Official External Apply URL"]].map(([name,label])=><label key={name}>{label}{name!=="payRange"&&" *"}<input style={input} name={name} required={name!=="payRange"} type={name.toLowerCase().includes("url")?"url":"text"}/></label>)}
 <label style={{gridColumn:"1/-1"}}>Short RNH-written summary *<textarea style={input} name="summary" required rows={4}/></label><label>Last Verified<input style={input} name="lastVerifiedAt" type="datetime-local"/></label><label>Review Due<input style={input} name="reviewDueAt" type="datetime-local"/></label><label>Status<select style={input} name="status" defaultValue="draft">{["draft","active","expired","retired","removed"].map(x=><option key={x}>{x}</option>)}</select></label><button style={{background:"#35806e",color:"white",border:0,borderRadius:9,fontWeight:800}}>Add Sourced Job</button></form>
 <div style={{display:"flex",gap:8,margin:"22px 0 10px"}}>{[["all","All"],["review","Needs Review"],["active","Active"],["expired","Expired"],["retired","Retired"]].map(([v,l])=><button key={v} onClick={()=>setFilter(v)}>{l}</button>)}</div>
 <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["Company","Job","Source","Status","Last Verified","Review Due","Actions"].map(x=><th key={x} style={{textAlign:"left",padding:10,borderBottom:"1px solid #ddd"}}>{x}</th>)}</tr></thead><tbody>{shown.map(j=><tr key={j.id}><td>{j.restaurant_name}</td><td>{j.title}<br/><small>{j.city}, {j.state}</small></td><td>RNH Sourced</td><td>{j.status}</td><td>{j.last_verified_at?new Date(j.last_verified_at).toLocaleDateString():"—"}</td><td>{j.review_due_at?new Date(j.review_due_at).toLocaleDateString():"—"}</td><td>{["verify","expire","retire","remove"].map(a=><button key={a} onClick={()=>action(j.id,a)} style={{margin:2}}>{a}</button>)}</td></tr>)}</tbody></table></div><h2>Company Sourced-job Analytics</h2>{analytics.map(a=><section key={a.companyId} style={{border:"1px solid #ddd",borderRadius:10,padding:14,marginBottom:12}}><h3>{a.companyName} {a.readyForOutreach&&<mark>Ready for Outreach</mark>}</h3><p><b>Active Sourced Jobs:</b> {a.activeSourcedJobs} · <b>Total Job Views:</b> {a.totalJobViews} · <b>Unique Viewers:</b> {a.uniqueViewers} · <b>Apply Clicks:</b> {a.applyClicks} · <b>Apply Click Rate:</b> {(a.applyClickRate*100).toFixed(1)}%</p><table><thead><tr><th>Job</th><th>Views</th><th>Unique Viewers</th><th>Apply Clicks</th></tr></thead><tbody>{a.jobs.map(j=><tr key={j.id}><td>{j.title}</td><td>{j.views}</td><td>{j.uniqueViewers}</td><td>{j.applyClicks}</td></tr>)}</tbody></table></section>)}</main>}
