"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CANDIDATE_RESOURCE_CATEGORIES, type CandidateResource, type CandidateResourceCategory, type CandidateResourceType } from "../../../lib/candidateResources";
import styles from "./admin.module.css";

type Form = { title:string; category:CandidateResourceCategory; resource_type:CandidateResourceType; url:string; source:string; description:string; thumbnail_url:string; sort_order:number; active:boolean };
const blank: Form = { title: "", category: CANDIDATE_RESOURCE_CATEGORIES[0], resource_type: "article", url: "", source: "", description: "", thumbnail_url: "", sort_order: 0, active: false };
export default function CandidateResourcesAdmin() {
 const [items,setItems]=useState<CandidateResource[]>([]),[form,setForm]=useState<Form>(blank),[editing,setEditing]=useState<string|null>(null),[message,setMessage]=useState(""),[search,setSearch]=useState(""),[category,setCategory]=useState("All"),[type,setType]=useState("All"),[status,setStatus]=useState("All");
 const load=useCallback(async()=>{const response=await fetch("/api/admin/candidate-resources");const body=await response.json();if(!response.ok){setMessage(body.error);return}setItems(body.resources)},[]);
 // Loading is an intentional external-system synchronization on first render.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>items.filter(i=>(!search||`${i.title} ${i.source}`.toLowerCase().includes(search.toLowerCase()))&&(category==="All"||i.category===category)&&(type==="All"||i.resource_type===type)&&(status==="All"||(status==="Published")===i.active)),[items,search,category,type,status]);
 function edit(i:CandidateResource){setEditing(i.id);setForm({title:i.title,category:i.category,resource_type:i.resource_type,url:i.url??"",source:i.source,description:i.description??"",thumbnail_url:i.thumbnail_url??"",sort_order:i.sort_order,active:i.active});window.scrollTo({top:0,behavior:"smooth"})}
 async function save(e:React.FormEvent){e.preventDefault();setMessage("Saving…");const response=await fetch(`/api/admin/candidate-resources${editing?`/${editing}`:""}`,{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const body=await response.json();if(!response.ok){setMessage(body.error);return}setForm(blank);setEditing(null);setMessage(editing?"Resource updated.":"Resource added.");await load()}
 async function remove(id:string){if(!window.confirm("Delete this resource permanently?"))return;const response=await fetch(`/api/admin/candidate-resources/${id}`,{method:"DELETE"});setMessage(response.ok?"Resource deleted.":(await response.json()).error);if(response.ok)await load()}
 async function toggle(i:CandidateResource){const response=await fetch(`/api/admin/candidate-resources/${i.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({...i,active:!i.active})});setMessage(response.ok?(i.active?"Resource hidden.":"Resource published."):(await response.json()).error);if(response.ok)await load()}
 const set=(key:keyof Form)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm(f=>({...f,[key]:key==="sort_order"?Number(e.target.value):e.target.value} as Form));
 return <main className={styles.page}><header><div><Link href="/admin">← Admin dashboard</Link><h1>Candidate Resources</h1><p>Add, publish, order, and maintain job-seeker resources.</p></div><Link href="/candidate-resources" target="_blank" rel="noopener noreferrer">View public page ↗</Link></header>
 <form onSubmit={save} className={styles.form}><h2>{editing?"Edit Resource":"Add Resource"}</h2><div className={styles.fields}><label>Title<input required value={form.title} onChange={set("title")}/></label><label>Category<select value={form.category} onChange={set("category")}>{CANDIDATE_RESOURCE_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label>Type<select value={form.resource_type} onChange={set("resource_type")}><option value="video">Video</option><option value="article">Article</option></select></label><label>URL<input type="url" value={form.url} onChange={set("url")} placeholder="May be blank while hidden"/></label><label>Source<input required value={form.source} onChange={set("source")}/></label><label>Thumbnail URL (optional)<input type="url" value={form.thumbnail_url} onChange={set("thumbnail_url")}/></label><label>Sort order<input type="number" value={form.sort_order} onChange={set("sort_order")}/></label><label className={styles.check}><input type="checkbox" checked={form.active} onChange={e=>setForm(f=>({...f,active:e.target.checked}))}/> Published</label><label className={styles.wide}>Description (optional)<textarea rows={3} value={form.description} onChange={set("description")}/></label></div><div className={styles.actions}><button type="submit">{editing?"Save Changes":"Add Resource"}</button>{editing&&<button type="button" className={styles.secondary} onClick={()=>{setEditing(null);setForm(blank)}}>Cancel</button>}<span role="status">{message}</span></div></form>
 <section className={styles.manage}><div className={styles.toolbar}><input aria-label="Search resources" placeholder="Search title or source" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter by category" value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{CANDIDATE_RESOURCE_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Filter by type" value={type} onChange={e=>setType(e.target.value)}><option>All</option><option value="video">Video</option><option value="article">Article</option></select><select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Published</option><option>Hidden</option></select></div><div className={styles.list}>{filtered.map(i=><article key={i.id}><div><span className={i.active?styles.published:styles.hidden}>{i.active?"Published":"Hidden"}</span><strong>{i.title}</strong><small>{i.category} · {i.resource_type} · Order {i.sort_order} · {i.source}</small></div><div><button onClick={()=>toggle(i)}>{i.active?"Hide":"Publish"}</button><button onClick={()=>edit(i)}>Edit</button><button className={styles.danger} onClick={()=>remove(i.id)}>Delete</button></div></article>)}</div></section></main>
}
