import assert from "node:assert/strict"; import { readFileSync } from "node:fs"; import test from "node:test";
const sql=readFileSync(new URL("./202609080002_promotional_email_verification.sql",import.meta.url),"utf8").toLowerCase(),route=readFileSync(new URL("../../app/api/promotional-entry/route.ts",import.meta.url),"utf8"),page=readFileSync(new URL("../../app/verify-promotional/[token]/page.tsx",import.meta.url),"utf8"),service=readFileSync(new URL("../../lib/promotionalVerification.ts",import.meta.url),"utf8");
test("submission atomically queues one encrypted verification email",()=>{assert.match(sql,/insert into public\.promotional_email_deliveries/);assert.match(sql,/token_ciphertext bytea/);assert.doesNotMatch(sql,/raw_token|plaintext/);assert.match(route,/dispatchPromotionalVerificationEmail/)});
test("delivery is concurrency safe retryable and provider-idempotent",()=>{assert.match(sql,/for update skip locked/);assert.match(sql,/claimed_at<now\(\)-interval '10 minutes'/);assert.match(sql,/retry_count=retry_count\+1/);assert.match(service,/Idempotency-Key/)});
test("valid redemption creates exactly one inactive pending unapproved job",()=>{assert.match(sql,/verification_token_digest=p_token_digest for update/);assert.match(sql,/insert into public\.jobs/);assert.match(sql,/'outreach_free',invitation\.id,false,'pending',null,null/);assert.match(sql,/redeemed_job_id=new_job_id/)});
test("invalid expired revoked and consumed tokens cannot create another job",()=>{assert.match(sql,/select 'invalid'/);assert.match(sql,/select 'already_used'/);assert.match(sql,/invitation\.revoked_at is not null/);assert.match(sql,/verification_expires_at<=now\(\)/)});
test("location redemption is permanent and verification starts no clock",()=>{assert.match(sql,/location_identity_key=invitation\.location_identity_key/);assert.match(sql,/i\.redeemed_job_id is not null/);assert.match(sql,/approved_at,expires_at/);assert.match(sql,/false,'pending',null,null/)});
test("RPC is service-only and page exposes safe customer states",()=>{assert.match(sql,/revoke all on function public\.redeem_public_promotional_verification\(bytea\) from public,anon,authenticated/);assert.match(sql,/grant execute on function public\.redeem_public_promotional_verification\(bytea\) to service_role/);assert.match(page,/Your job has been submitted for review/);assert.match(page,/already_used/);assert.doesNotMatch(page,/job_id|eligibility_reason|revoked_at/)});
test("promotion does not touch billing subscriptions or quantities",()=>assert.doesNotMatch(sql+route,/stripe|subscription|quantity|billing/i));
