import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
const sql=readFileSync(new URL("./202609030001_harden_public_promotional_entry.sql",import.meta.url),"utf8").toLowerCase();
test("every company insert and name update receives the database canonical identity",()=>{assert.match(sql,/create trigger companies_set_identity_key/);assert.match(sql,/before insert or update of name, identity_key/);assert.match(sql,/new\.identity_key := public\.normalize_company_identity\(new\.name\)/);assert.match(sql,/lower\(regexp_replace\(btrim\(company_name\), '\\s\+', ' ', 'g'\)\)/);});
test("promotional company resolution uses the same database normalizer and serializes creation",()=>{assert.match(sql,/company_identity := public\.normalize_company_identity\(p_name\)/);assert.match(sql,/pg_advisory_xact_lock\(hashtextextended\(company_identity, 31\)\)/);assert.match(sql,/where identity_key = company_identity/);});
test("concurrent rate admissions serialize on both identities before counting and inserting",()=>{const ip=sql.indexOf("pg_advisory_xact_lock(hashtextextended(encode(p_ip_digest");const email=sql.indexOf("pg_advisory_xact_lock(hashtextextended(p_contact_email");const count=sql.indexOf("select count(*) into ip_count");const insert=sql.indexOf("insert into public.promotional_entry_attempts");assert.ok(ip>0&&email>ip&&count>email&&insert>count);assert.match(sql,/if ip_count >= 5 or email_count >= 3 then return false/);assert.equal((sql.match(/insert into public\.promotional_entry_attempts/g)??[]).length,1);});
test("attempt retention removes records after 24 hours and is service-role only",()=>{assert.match(sql,/attempted_at < now\(\) - interval '24 hours'/);assert.match(sql,/grant execute on function public\.cleanup_promotional_entry_attempts\(\) to service_role/);assert.match(sql,/revoke all on function public\.cleanup_promotional_entry_attempts\(\) from public, anon, authenticated/);});
test("public roles cannot call company or admission security-definer functions",()=>{for(const signature of ["resolve_promotional_company\\(text, text\\)","admit_promotional_entry_attempt\\(bytea, text\\)"])assert.match(sql,new RegExp(`revoke all on function public\\.${signature} from public, anon, authenticated`));});
